[package]
name = "jwtk"
version = "0.3.0"
edition = "2018"
repository = "https://github.com/sopium/jwtk"
license = "MIT"
description = "JWT signing (JWS) and verification, with first class JWK and JWK Set (JWKS) support."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["remote-jwks"]
remote-jwks = ["reqwest", "tokio"]

[dependencies]
base64 = "0.13.0"
openssl = "0.10.35"
serde = { version = "1.0.127", features = ["derive"] }
serde_json = "1.0.66"
smallvec = "1.6.1"
reqwest = { version = "0.11.4", features = ["json"], optional = true }
tokio = { version = "1.9.0", features = ["sync"], optional = true }
openssl-sys = "0.9.65"
foreign-types = "0.3.2"
serde_with = "3.1.0"

[dev-dependencies]
axum = "0.1.3"
tokio = { version = "1.9.0", features = ["macros", "rt-multi-thread"] }
